contributors:
  - repository: Netcracker/base-images-module-base
    users: []
    role: push
    action: add
  - repository: Netcracker/cla-storage
    users: []
    role: push
    action: add
  - repository: Netcracker/gatekeeper-library
    users: []
    role: push
    action: add
  - repository: Netcracker/get-package-ids
    users: []
    role: push
    action: add
  - repository: Netcracker/k8s-conformance
    users: []
    role: push
    action: add
  - repository: Netcracker/KubeMarine
    users: []
    role: push
    action: add
  - repository: Netcracker/pg_hint_plan
    users: []
    role: push
    action: add
  - repository: Netcracker/pgskipper-operator-core
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-agent
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-api-data-model
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-api-diff
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-api-doc-viewer
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-api-processor
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-api-unifier
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-api-visitor
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-apispec-view
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-backend
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-build-task-consumer
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-ci
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-class-view
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-compatibility-suites
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-graphapi
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-http-spec
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-jest-chrome-in-docker-environment
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-json-crawl
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-nodejs-dev-image
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-npm-gitflow
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-postman-collections
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-protobufjs-research
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-rest-playground
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-sniffer-agent
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-test-service
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-traffic-analyzer
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-ui
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-ui-tests
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-apihub-vscode
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-backup-daemon
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-cloud-core-context-propagation
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-cloud-passport-cli
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-consul
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-consul-acl-configurator
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-consul-backup-daemon
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-arquillian-cube-extension
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-blue-green-state-monitor-java
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-blue-green-state-monitor-quarkus
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-commons
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-context-propagation
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-error-handling
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-microservice-dependencies
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-microservice-framework
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-microservice-framework-extensions
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-mongo-evolution
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-okhttpm2mclient
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-quarkus-extensions
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-rest-libraries
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-restclient
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-core-springboot-starter
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-credential-manager
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-dbaas
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-dbaas-adapter-core
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-dbaas-client
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-deployment-status-provisioner
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-diag-proxy
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-disaster-recovery-daemon
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-docker-integration-tests
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-docker-opensearch
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-env-checker
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-envgene
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-external-logging-installer
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-fluent-pipeline-tests
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-fluentd
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-git-system-follower
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-grafana-plugins-init
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-grafana-reporter
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-graphite-remote-adapter
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-graylog-archiving-plugin
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-graylog-obfuscation-plugin
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-hive-metastore
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-integration-catalog-library
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-integration-designtime-catalog
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-integration-engine
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-integration-platform
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-integration-runtime-catalog
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-integration-sessions-management
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-integration-variables-management
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-inventory-tool-cli
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-inventory-tool-core
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-jaeger
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-kube-events-generator
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-kube-events-reader
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-log-exporter
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-log-generator
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-logging-operator
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-maas
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-maas-client
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-maas-client-quarkus
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-maas-client-spring
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-maas-declarative-client-commons
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-maas-declarative-client-quarkus
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-maas-declarative-client-spring
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-mistral
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-network-latency-exporter
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-open-telemetry-collector
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-opensearch
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-opensearch-curator
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-opensearch-dbaas-adapter
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-opensearch-monitoring
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-pipelines-common-python-library
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-profiler-agent
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-prometheus-adapter-operator
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-renovate-config
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-repo-template
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-tcp-duplicator
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-test-pipelines
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-version-exporter
    users: []
    role: push
    action: add
  - repository: Netcracker/qubership-workflow-hub
    users: []
    role: push
    action: add
