---

name: Automatic PR Labeler

on:
  pull_request:
    branches: [main]
    types:
      [opened, reopened]
permissions:
  pull-requests: write
  contents: read
  issues: write
jobs:
  assign-labels:
    uses: netcracker/qubership-workflow-hub/.github/workflows/auto-labeler.yaml@v1.0.0
    name: Assign labels in pull request
    if: github.event.pull_request.merged == false
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
      config_file: './.github/auto-labeler-config.yaml'
